TwoIsland_House_Text_TeachMonMoveForMushroom:: @ 81A2B88
	.string "I'm the POKéMON MOVE MANIAC.\p"
	.string "I know every single move that\n"
	.string "POKéMON learn growing up.\p"
	.string "I'm also a mushroom maniac.\p"
	.string "Bring me two TINYMUSHROOMS,\n"
	.string "or one BIG MUSHROOM.\p"
	.string "If you do that for me, I'll teach\n"
	.string "a move to one POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove:: @ 81A2C63
	.string "Sniff, sniff…\n"
	.string "Hm! You smell of MUSHROOMS!\p"
	.string "Do you want me to teach a move\n"
	.string "to a POKéMON of yours?$"

TwoIsland_House_Text_TutorWhichMon:: @ 81A2CC3
	.string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove:: @ 81A2CE1
	.string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon:: @ 81A2CFC
	.string "Sorry…\p"
	.string "It doesn't appear as if I have a\n"
	.string "move I can teach that POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo:: @ 81A2D43
	.string "Then, I'll need a MUSHROOM or two.\n"
	.string "What are you going to give me?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms:: @ 81A2D85
	.string "{PLAYER} handed over two\n"
	.string "TINYMUSHROOMS in exchange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom:: @ 81A2DB3
	.string "{PLAYER} handed over one\n"
	.string "BIG MUSHROOM in exchange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove:: @ 81A2DE0
	.string "If your POKéMON need to learn a\n"
	.string "move, I need a MUSHROOM or two.$"

TwoIsland_House_Text_CantTeachAnEgg:: @ 81A2E20
	.string "Hunh? There isn't a single move\n"
	.string "that I can teach an EGG.$"

TwoIsland_House_Text_OhYourPokemon: @ 81DD68A
	.string "Oh?\n"
	.string "Your {STR_VAR_1}…$"

TwoIsland_House_Text_PleaseGiveItThisEffortRibbon: @ 81DD697
	.string "Went for it stupendously!\p"
	.string "As its reward, please give it this\n"
	.string "EFFORT RIBBON.$"

TwoIsland_House_Text_ReceivedEffortRibbon: @ 81DD6E3
	.string "{COLOR DARK_GRAY}{PLAYER} received the EFFORT RIBBON.$"

TwoIsland_House_Text_PutEffortRibbonOnMon: @ 81DD702
	.string "{COLOR DARK_GRAY}{PLAYER} put the EFFORT RIBBON\n"
	.string "on {STR_VAR_1}.$"

TwoIsland_House_Text_GoForItLittleHarder: @ 81DD722
	.string "You have to go for it a\n"
	.string "little harder.\p"
	.string "If you do, I'll give your POKéMON\n"
	.string "something nice.$"

TwoIsland_House_Text_EffortRibbonLooksGoodOnIt: @ 81DD77B
	.string "Oh! Your {STR_VAR_1}, that EFFORT\n"
	.string "RIBBON looks good on it!$"

TwoIsland_House_Text_Paras::
	.string "PARAS: Paras!$"

TwoIsland_House_Text_PleaseTradeParas::
	.string "Do you happen to have a PARAS?\n"
	.string "Gimme gimme!$"

TwoIsland_House_Text_HappyToHelp::
	.string "If your POKéMON need to learn a\n"
	.string "move, I'm happy to help!$"

TwoIsland_House_Text_ParasAreDoingWell::
	.string "My PARAS are all doing well and\n"
	.string "I have all the MUSHROOMS I could\l"
	.string "ever ask for!$"

TwoIsland_House_Text_WantMeToTeachMoveQuestCompleted::
	.string "Do you want me to teach a move\n"
	.string "to a POKéMON of yours?$"

TwoIsland_House_Text_HandedOverParas::
	.string "{PLAYER} handed over PARAS\n"
	.string "to POKéMON MOVE MANIAC.$"

TwoIsland_House_Text_ParasStory::
	.string "You come here a lot and you seem\n"
	.string "to be a pretty strong trainer.\p"
	.string "I wonder if you can do me a favor?\n"
	.string "I've heard PARAS can grow\l"
	.string "TINYMUSHROOMS!\p"
	.string "If you bring me 5 PARAS, I'll\n"
	.string "teach your POKéMON moves for free.$"

